import type { DeepTutorial } from '../deep-types';

export const LINUX_DEEP_TUTORIALS_41: Record<string, DeepTutorial> = {
  "xk5Xgi797HlVjdZJRfwX1": {
    mentalModel: '检查服务状态不只是 systemctl status——还要看日志、端口响应、资源使用。active 不代表健康。',
    handsOn: [
      { title: 'systemd 状态', cmd: 'systemctl status nginx', output: '● nginx.service - A high performance web server\n     Loaded: loaded (/lib/systemd/system/nginx.service; enabled)\n     Active: active (running) since Mon 2024-01-15 09:00:00 UTC; 5h ago\n   Main PID: 5678 (nginx)\n      Tasks: 3 (limit: 4659)\n     Memory: 12.3M', explain: 'Active: active (running) 只是 systemd 层面的状态。进程可能在跑但内部已出错（如数据库连接断了）。' },
      { title: '应用层健康检查', cmd: 'curl -f http://localhost/health || echo "UNHEALTHY"', output: '{"status":"ok","version":"1.2.3"}', explain: '好的应用暴露 /health 或 /healthz 端点。返回 200 = 健康，503 = 不健康。curl -f 在非 200 时返回错误码。' },
      { title: '端口检查', cmd: 'ss -tlnp | grep :80', output: 'LISTEN 0      511    0.0.0.0:80        0.0.0.0:*    users:(("nginx",pid=5678,fd=6))', explain: '服务 active 但端口没监听 = 启动过程中出错了。ss -tlnp 看所有监听端口和对应进程。' },
      { title: '资源使用', cmd: 'top -bn1 | grep nginx', output: ' 5678 www-data  20   0  123456  12345   0.0  0.8  0:05.23 nginx', explain: 'top -bn1 非交互模式输出一帧。看 %CPU 和 %MEM。CPU 100% = 有性能问题。内存持续增长 = 可能内存泄漏。' },
    ],
    diagnosis: [
      { symptom: 'systemctl status 显示 active 但用户报 API 超时', cause: '服务进程在跑但内部有问题（线程死锁、连接池耗尽、磁盘满写不了日志）。', fix: 'curl /health 检查应用层。journalctl -u service 看日志。df -h 看日志盘是否快满。' },
      { symptom: '服务频繁重启', cause: '程序崩溃或健康检查失败。systemd 的 Restart=on-failure 会自动重启。', fix: 'journalctl -u service --since "1 hour ago" 看崩溃日志。systemctl show service -p NRestarts 看重启次数。' },
      { symptom: '服务启动很慢', cause: '启动脚本做了太多事（如等待数据库就绪、DNS 解析超时）。', fix: 'systemd-analyze blame 看哪个服务启动最慢。systemd-analyze critical-chain service 看依赖链。' },
    ],
    exercises: [
      { level: '基础', task: '写一个"服务健康检查"脚本，检查 systemd 状态、端口监听、HTTP 响应', hint: 'systemctl is-active + ss + curl', answer: '#!/bin/bash\nSERVICE=${1:-nginx}\nPORT=${2:-80}\nHEALTH_URL=${3:-"http://localhost/health"}\n\necho "=== $SERVICE 健康检查 ==="\necho ""\n\n# 1. systemd 状态\necho "--- systemd 状态 ---"\nif systemctl is-active --quiet "$SERVICE"; then\n  echo "✓ 服务运行中"\nelse\n  echo "✗ 服务未运行"\n  systemctl status "$SERVICE" --no-pager\n  exit 1\nfi\n\n# 2. 端口监听\necho ""\necho "--- 端口监听 ---"\nif ss -tlnp | grep -q ":$PORT"; then\n  echo "✓ 端口 $PORT 监听中"\nelse\n  echo "✗ 端口 $PORT 未监听"\n  exit 1\nfi\n\n# 3. HTTP 响应\necho ""\necho "--- HTTP 响应 ---"\nHTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL")\nif [ "$HTTP_CODE" = "200" ]; then\n  echo "✓ HTTP 200 OK"\nelse\n  echo "✗ HTTP $HTTP_CODE"\n  exit 1\nfi\n\necho ""\necho "所有检查通过"' },
      { level: '进阶', task: '写一个"服务监控仪表盘"，实时显示多个服务的状态', hint: 'watch + systemctl + ss', answer: '#!/bin/bash\nSERVICES="nginx postgresql redis docker"\n\nwhile true; do\n  clear\n  echo "=== 服务监控仪表盘 $(date) ==="\n  echo ""\n  printf "%-20s %-10s %-10s %-15s\\n" "服务" "状态" "端口" "内存"\n  printf "%-20s %-10s %-10s %-15s\\n" "---" "---" "---" "---"\n  \n  for svc in $SERVICES; do\n    # 状态\n    if systemctl is-active --quiet "$svc"; then\n      status="● 运行中"\n    else\n      status="○ 停止"\n    fi\n    \n    # 端口（假设服务名和端口映射）\n    case "$svc" in\n      nginx) port="80" ;;\n      postgresql) port="5432" ;;\n      redis) port="6379" ;;\n      docker) port="2376" ;;\n      *) port="?" ;;\n    esac\n    \n    if ss -tlnp | grep -q ":$port"; then\n      port_status="✓ $port"\n    else\n      port_status="✗ $port"\n    fi\n    \n    # 内存\n    pid=$(pgrep -f "$svc" | head -1)\n    if [ -n "$pid" ]; then\n      mem=$(ps -p "$pid" -o rss= | awk \'{printf "%.1fMB", $1/1024}\')\n    else\n      mem="-"\n    fi\n    \n    printf "%-20s %-10s %-10s %-15s\\n" "$svc" "$status" "$port_status" "$mem"\n  done\n  \n  echo ""\n  echo "按 Ctrl+C 退出"\n  sleep 5\ndone' },
      { level: '挑战', task: '写一个"自动故障诊断"脚本，服务挂掉时自动收集信息并生成报告', hint: 'systemctl status + journalctl + top + 生成 markdown 报告', answer: '#!/bin/bash\nSERVICE=${1:-nginx}\nREPORT="/tmp/diagnosis-$(date +%Y%m%d-%H%M%S).md"\n\nif systemctl is-active --quiet "$SERVICE"; then\n  echo "服务正常运行，无需诊断"\n  exit 0\nfi\n\necho "=== 自动故障诊断: $SERVICE ==="\necho "生成报告: $REPORT"\n\ncat > "$REPORT" << EOF\n# $SERVICE 故障诊断报告\n\n**时间**: $(date)\n**主机**: $(hostname)\n\n## 1. systemd 状态\n\n\\\`\\\`\\\`\n$(systemctl status "$SERVICE" --no-pager 2>&1)\n\\\`\\\`\\\`\n\n## 2. 最近日志（最后 100 行）\n\n\\\`\\\`\\\`\n$(journalctl -u "$SERVICE" -n 100 --no-pager 2>&1)\n\\\`\\\`\\\`\n\n## 3. 系统资源\n\n### 负载\n\\\`\\\`\\\`\n$(uptime)\n\\\`\\\`\\\`\n\n### 内存\n\\\`\\\`\\\`\n$(free -h)\n\\\`\\\`\\\`\n\n### 磁盘\n\\\`\\\`\\\`\n$(df -h)\n\\\`\\\`\\\`\n\n## 4. 相关进程\n\n\\\`\\\`\\\`\n$(ps aux | grep -E "$SERVICE|postgres|mysql|redis" | grep -v grep)\n\\\`\\\`\\\`\n\n## 5. 网络状态\n\n\\\`\\\`\\\`\n$(ss -tlnp)\n\\\`\\\`\\\`\n\n## 6. 可能的原因\n\n- 配置文件语法错误\n- 端口被占用\n- 依赖服务未启动\n- 磁盘空间不足\n- 内存不足\n\n## 7. 建议操作\n\n1. 检查日志中的错误信息\n2. 验证配置文件语法\n3. 确认依赖服务运行正常\n4. 检查系统资源使用情况\nEOF\n\necho "报告已生成: $REPORT"\necho ""\necho "可能的原因（从日志提取）:"\njournalctl -u "$SERVICE" -n 50 --no-pager | grep -iE "error|fail|denied" | tail -5' },
    ],
    prereqs: ['systemctl — 服务管理', 'journalctl — 日志查看'],
    nextSteps: ['监控工具 — Prometheus/Grafana', '告警系统 — Alertmanager'],
  },
};
