import type { DeepTutorial } from '../deep-types';

export const POSTGRESQL_DEEP_TUTORIALS_16: Record<string, DeepTutorial> = {
  "o1WSsw-ZIaAb8JF3P0mfR": { mentalModel: 'GRANT/REVOKE 是 PG 的"权限开关"——GRANT 给钥匙（权限），REVOKE 收回钥匙。可以精确到：谁能（user/role）、对什么（table/schema/database）、做什么（SELECT/INSERT/UPDATE/DELETE）。', sections: [{ title: '权限管理', content: 'GRANT SELECT, INSERT ON orders TO app_user; GRANT ALL ON ALL TABLES IN SCHEMA public TO admin; GRANT USAGE ON SCHEMA public TO readonly; REVOKE DELETE ON orders FROM app_user; 查看权限：\\dp tablename 或 SELECT * FROM information_schema.table_privileges; 默认权限：ALTER DEFAULT PRIVILEGES FOR ROLE admin GRANT SELECT ON TABLES TO readonly;（以后 admin 创建的表自动授权给 readonly）。' }],
    diagnosis: [
      { symptom: 'REVOKE 后用户仍能访问表——撤销不生效', cause: '用户通过多路径获得权限——直接 GRANT+组角色继承。REVOKE 只撤销直接授予不撤销组角色继承。', fix: '检查所有权限来源：SELECT grantee,table_name,privilege_type FROM information_schema.table_privileges; REVOKE 所有来源或用 DROP OWNED BY 清理。' },
      { symptom: 'GRANT ALL ON ALL TABLES 后新表无权限', cause: 'GRANT ON ALL TABLES 只影响当前已存在表——新表不自动继承。需 ALTER DEFAULT PRIVILEGES。', fix: 'ALTER DEFAULT PRIVILEGES FOR ROLE 创建者 IN SCHEMA public GRANT SELECT ON TABLES TO 只读用户;\ddp 确认。对已存在表另行 GRANT。' },
    ],
  exercises: [{ level: '基础', task: '创建一个只读用户并只授予 orders 表的 SELECT 权限', hint: 'CREATE ROLE + GRANT SELECT', answer: "CREATE ROLE reader WITH LOGIN PASSWORD 'pw'; GRANT CONNECT ON DATABASE mydb TO reader; GRANT USAGE ON SCHEMA public TO reader; GRANT SELECT ON orders TO reader; 这个用户只能 SELECT orders，其他表都看不了。" }] },
  "wH447bS-csqmGbk-jaGqp": { mentalModel: 'perf-tools 是 Brendan Gregg 出品的 Linux 性能工具集——基于 perf/ftrace 的 shell 脚本。比原生 perf 更易用。execsnoop（看谁在启动新进程）、opensnoop（看谁在打开文件）、tcptop（看 TCP 连接）。', sections: [{ title: 'perf-tools 在 PG 中的应用', content: 'execsnoop：看是否有异常进程被 PG 触发。opensnoop：看 PG 在读写哪些文件（data/WAL/log）。tcptop：看 PG 客户端连接的流量。funcgraph：追踪 PG 内部的函数调用。对 DBA——perf-tools 让你从 OS 层面观测 PG 行为而不依赖 PG 自身的工具。' }],
    diagnosis: [
      { symptom: 'opensnoop 追踪 PG 显示大量对 base/ 目录随机读', cause: '正常索引扫描行为——PG 通过索引定位数据页后随机读。大量随机读说明查询用索引但回表 IO 仍大。', fix: '检查频繁读取表的索引。建覆盖索引减回表。加大 shared_buffers 提高缓存命中。pg_stat_statements 定位查询。' },
      { symptom: 'tcptop 显示 PG 流量异常——某连接持续传数百 MB', cause: '大查询结果集——SELECT * FROM 大表无 LIMIT，或 pg_dump 备份或流复制 WAL 发送。', fix: 'pg_stat_activity 找到对应连接查询。不必要的全表导出→终止。流复制流量正常。检查日志。' },
    ],
  exercises: [{ level: '进阶', task: '用 opensnoop 查看 PG 进程在读写哪些文件', hint: 'opensnoop -p PID', answer: 'opensnoop -p $(pgrep -f "postgres: .* idle" | head -1) 实时看 PG 在打开哪些文件。包括数据文件（base/...）、WAL（pg_wal/...）和日志文件。' }] },
  "gb75xOcAr-q8TcA6_l1GZ": { mentalModel: 'PG 认证模型——不只是密码（scram-sha-256），还支持 peer（OS 用户匹配）、cert（客户端证书）、LDAP（企业目录服务）、GSSAPI（Kerberos）、RADIUS。大多场景用 scram-sha-256 就够了。', sections: [{ title: '认证方式选择', content: 'scram-sha-256：推荐。peer：本地连接最简单（psql -U postgres 不需要密码——OS 用户名和 PG 用户名一致）。cert：最高安全等级，客户端持有证书才能连。LDAP：企业统一账号。GSSAPI/Kerberos：单点登录集成。配置在 pg_hba.conf 的 METHOD 列。推荐：本地开发用 peer/trust，生产用 scram-sha-256，高安全要求用 cert。' }],
    diagnosis: [
      { symptom: 'cert 认证配置后客户端报 "certificate verify failed"', cause: '客户端未提供证书或证书未被服务器信任。ssl_ca_file 未正确配置 CA 证书链。', fix: '确保服务器设 ssl_ca_file。客户端提供证书：psql "sslcert=client.crt sslkey=client.key sslrootcert=ca.crt"。验证：SELECT ssl,issuer,subject FROM pg_stat_ssl。' },
      { symptom: 'LDAP 认证部分用户无法登录——LDAP 连接超时', cause: 'LDAP 服务器网络不通或响应超时。pg_hba.conf LDAP URL 配置错误或 search bind 参数不匹配。', fix: 'ldapsearch 验证连接和搜索。pg_hba.conf 确保 ldapserver/ldapprefix/ldapsuffix 正确。ldaptls=1 开启 TLS。' },
    ],
  exercises: [{ level: '基础', task: 'peer 认证是什么场景用的', hint: '不需要密码', answer: '本地 Unix socket 连接时，如果 OS 用户名和 PG 用户名一样，peer 认证不需要密码。常用于：服务器的定时备份脚本（OS 用户 postgres 连 PG 用户 postgres）。' }] },
  "aXG68inOu3trBWOmg9Yqx": { mentalModel: 'temBoard 是法国 Dalibo 公司开发的 PG 远程管理和监控工具——Web UI 界面管理多个 PG 实例。Agent 装在 PG 服务器上，向中央 temBoard Server 上报状态。', sections: [{ title: 'temBoard 的定位', content: '适合：管理几十个 PG 实例的 DBA 团队——一个 Web 页面看所有实例的健康度/配置。核心功能：实时监控面板、配置管理、SQL 执行、告警通知。temBoard 是企业级工具——个人/小团队用 pgcenter + Grafana 就够了。' }],
    diagnosis: [
      { symptom: 'temBoard agent 失联——Web UI 显示 agent 离线', cause: 'agent 进程挂了或网络不通。SSL 证书过期。或 agent 配置的 temBoard server URL 错误。', fix: 'systemctl status temboard-agent。journalctl -u temboard-agent。temboard-agent register 重新注册。SSL 问题重新生成证书。' },
      { symptom: 'temBoard 替代方案——小团队太重', cause: 'temBoard 需 agent+server+PG 元数据库——部署复杂。小团队 2-3 PG 实例不值得。', fix: '小团队用 pgcenter+Grafana+pg_stat_statements 零部署组合。或用 pgAdmin 4 Web 模式。云环境用云厂商监控。' },
    ],
  exercises: [{ level: '基础', task: '小团队 vs 企业的 PG 监控工具推荐', hint: 'Prometheus vs temBoard', answer: '小团队：Prometheus + postgres_exporter + Grafana（开源免费、社区支持好）。企业多实例：temBoard 或 pgAdmin 4 Web（集中管理多实例、有 GUI）。云环境：云厂商的控制台监控（RDS Performance Insights/Cloud SQL Insights）。' }] },
  "zoaqBP0Jbf0HpTH8Q3LkJ": { mentalModel: 'VACUUM 详解——普通 VACUUM（回收死元组、更新统计、不锁表、不还磁盘）、VACUUM FULL（重写表、还磁盘、锁表）、autovacuum（自动跑）。', sections: [{ title: 'VACUUM 调优', content: 'vacuum_cost_delay：VACUUM 每做多少工作 sleep 一下（默认 2ms）。降低可以让 VACUUM 更快但也影响线上查询。autovacuum_max_workers：最多几个 autovacuum 并发（默认 3）。对多表高频更新需调大。autovacuum_naptime：autovacuum 每轮检查间隔（默认 1min）。pg_stat_user_tables.n_dead_tup / n_live_tup：死/活元组比——太高说明 VACUUM 跟不上。' }], diagnosis: [{ symptom: 'DELETE 了很多数据但磁盘没释放', cause: 'VACUUM 回收的死元组空间是"标记可重用"而非"还给 OS"。', fix: '普通 VACUUM 不释放磁盘。需要用 VACUUM FULL（锁表、重写）或 pg_repack（在线整理）来真正还给 OS 磁盘空间。但生产环境别轻易 VACUUM FULL——锁表期间连 SELECT 都阻塞。' }], exercises: [{ level: '进阶', task: '检查一张表有多少死元组，判断是否需要手动 VACUUM', hint: 'pg_stat_user_tables + n_dead_tup', answer: 'SELECT relname, n_live_tup, n_dead_tup, n_dead_tup * 100.0 / NULLIF(n_live_tup + n_dead_tup, 0) AS dead_ratio FROM pg_stat_user_tables WHERE relname = \'orders\'; dead_ratio > 20% → 该手动 VACUUM 或调低该表的 autovacuum 阈值。' }] },
  "WCBWPubUS84r3tOXpnZT3": { mentalModel: 'PgQ（PostgreSQL Queue）——用 PG 做任务队列！基于 SKIP LOCKED 的简单队列。不需要 Kafka/RabbitMQ，PG 就能做轻量级任务队列。', sections: [{ title: 'PG 做任务队列', content: '原理：tasks 表（id, payload, status, created_at）。入队：INSERT INTO tasks (payload) VALUES (\'...\'); 出队：SELECT id, payload FROM tasks WHERE status=\'pending\' ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1; 完成后：UPDATE tasks SET status=\'done\' WHERE id=$1。SKIP LOCKED 保证多个 worker 不会抢同一个任务。优势：不需要额外基础设施、和业务数据一起管理。限制：不适合高吞吐（>1000 QPS）、长时间运行的任务。' }],
    diagnosis: [
      { symptom: 'PG 做任务队列后表飞速膨胀——几百万行未清理', cause: '完成/失败任务未删除——不断积累。任务表膨胀+无 VACUUM 致查询变慢。', fix: "定期清理：DELETE FROM queue WHERE status IN('done','failed') AND created_at<now()-interval'7 days'; 建部分索引。设高频 autovacuum。" },
      { symptom: '多 worker 竞争 SKIP LOCKED 扫描浪费 CPU', cause: '大量 worker 同时 SKIP LOCKED 扫描——每个 scan 从表头跳过已锁定行。worker 越多浪费越严重。', fix: 'LISTEN/NOTIFY 替代轮询：INSERT 后 NOTIFY task_added; worker LISTEN 收通知后取任务。任务量>1000 QPS→考虑专用消息队列。' },
    ],
  exercises: [{ level: '进阶', task: '用 PG 实现一个简单任务队列（入队+出队+完成标记）', hint: 'FOR UPDATE SKIP LOCKED', answer: '入队：INSERT INTO queue(payload) VALUES(\'{"type":"email","to":"a@b.com"}\'); 出队：BEGIN; SELECT id, payload FROM queue WHERE status=\'pending\' ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1; UPDATE queue SET status=\'processing\' WHERE id=$id; COMMIT; 完成：UPDATE queue SET status=\'done\' WHERE id=$id; 失败：UPDATE queue SET status=\'failed\', retries=retries+1 WHERE id=$id;' }] },
  "v3SoKmeCh6uxKW5GAAMje": { mentalModel: 'pg_ctlcluster 是 Debian/Ubuntu 的 PG 多版本管理命令——一台机器装多个 PG 版本（14、15、16），用 pg_ctlcluster 分别管理。比 pg_ctl 多了"版本+集群名"的概念。', sections: [{ title: 'pg_ctlcluster 使用', content: '命令格式：pg_ctlcluster VERSION CLUSTER ACTION。如 pg_ctlcluster 16 main start/stop/restart/status。列出所有集群：pg_lsclusters。创建新集群：pg_createcluster 16 myapp --port=5433。Debian/Ubuntu 通过 apt 安装 PG 后自动创建 main 集群，用 pg_ctlcluster 管理。在其他发行版上直接用 pg_ctl。' }],
    diagnosis: [
      { symptom: 'pg_lsclusters 列出集群显示 "down"——明明在运行', cause: 'pg_ctlcluster 状态检测依赖 pg_ctl status——unix socket 目录或 postmaster.pid 路径不同导致误判。', fix: '手动 pg_ctl -D /data status。ps aux | grep postgres 确认进程。状态不准用 pg_ctl 或 systemctl status 替代。' },
      { symptom: 'pg_createcluster 后连接报 "database does not exist"', cause: 'pg_createcluster 只初始化数据目录和配置文件——未 CREATE DATABASE。', fix: '启动集群后 psql -U postgres -p 端口 → CREATE DATABASE mydb; 或用 createdb 创建。pg_lsclusters 确认端口和状态。' },
    ],
  exercises: [{ level: '基础', task: '检查当前系统上安装了多少个 PG 集群', hint: 'pg_lsclusters', answer: 'pg_lsclusters 列出所有 PG 集群的版本、名称、状态、数据目录、端口。一台机器跑多个 PG 版本（14/main + 15/main + 16/main）很常见用于测试升级。' }] },
  "pEtQy1nuW98YUwrbfs7Np": { mentalModel: 'Package Managers 管理 PG 软件包——apt（Debian/Ubuntu）、yum/dnf（RHEL/CentOS）、brew（macOS）、官方 YUM/APT repository 提供最新版本。不用从源码编译。', sections: [{ title: '安装 PG 的多种方式', content: 'apt：sudo apt install postgresql-16。官方 APT 仓库（推荐）：sudo sh -c \'echo "deb http://apt.postgresql.org/pub/repos/apt ..."\' 后 apt 安装——确保拿到最新版本而非系统自带的旧版。Docker：docker run postgres:16-alpine（最简单）。源码编译：./configure && make && make install（最灵活但复杂）。推荐开发和生产都用官方仓库或 Docker——版本可控、安全更新及时。' }],
    diagnosis: [
      { symptom: 'apt install postgresql 安装了 PG 12 而非想要的 PG 16', cause: '系统仓库的 PG 版本是 OS 自带旧版本——未添加 PG 官方 APT 仓库。', fix: '添加 PG 官方 APT 仓库→apt update→apt install postgresql-16。apt policy postgresql 确认版本。' },
      { symptom: 'brew 安装 PG 开发正常但 Linux 生产出错', cause: 'macOS 和 Linux 上 PG 某些行为不同——文件路径、locale 默认值、系统调用差异。', fix: "开发环境和生产一致——用 Docker postgres:16 镜像。CREATE DATABASE ... LOCALE='en_US.UTF-8' 显式指定 locale。" },
    ],
  exercises: [{ level: '基础', task: 'Ubuntu 上用官方 APT 仓库安装 PG 16', hint: '添加官方源→apt update→apt install', answer: 'sudo sh -c \'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list\'; wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -; sudo apt update; sudo apt install postgresql-16' }] },
  "ga8ZiuPc42XvZ3-iVh8T1": { mentalModel: 'For Tables 是 PG 中的"表级循环/游标"——不是每种语言都有专门的语法。在 PL/pgSQL 中 FOR row IN SELECT ... LOOP 遍历查询结果做逐行处理。', sections: [{ title: '游标和循环', content: 'FOR IN LOOP：FOR rec IN SELECT id, name FROM users LOOP RAISE NOTICE \'Processing user %\', rec.name; END LOOP;。游标：DECLARE cur CURSOR FOR SELECT ...; OPEN/FETCH/CLOSE（适合增量处理超大数据集）。游标和 FOR 循环的区别：FOR 一次全部加载、游标逐行/逐批取出（节省内存）。批量 DML 避免用逐行循环——一条 UPDATE/INSERT ... SELECT 比循环快 100 倍。' }],
    diagnosis: [
      { symptom: '游标（CURSOR）打开后忘关闭——事务一直持有资源', cause: '游标在事务内有效——事务未 COMMIT/ROLLBACK 且游标未 CLOSE，游标持有查询资源和锁持续占用。', fix: '事务结束确保 CLOSE cursor 或 COMMIT 自动关闭。设 statement_timeout 防单个 FETCH 太久。WITH HOLD 游标也需显式 CLOSE。' },
      { symptom: 'FOR IN LOOP 处理 10 万行花了几分钟——太慢', cause: '逐行处理——每行需独立执行上下文切换。10 万行=10 万次 PL/pgSQL 解释+SQL 执行来回。', fix: '批量处理替代循环：一条 UPDATE/INSERT FROM 替代循环。必须循环→每 1000 行 COMMIT 避免长事务。原则：SQL 做集合操作。' },
    ],
  exercises: [{ level: '基础', task: '为什么批量 UPDATE 比逐行循环快', hint: 'SQL 是集合操作', answer: 'SQL 天生是集合操作——UPDATE ... WHERE ... 一次性处理所有匹配的行。逐行循环 = 每条 SQL 都是一次独立的解析-执行-返回-提交的开销。1000 行循环 = 1000 次来回。批量 UPDATE 可能只需要 1 次。' }] },
  "t18XjeHP4uRyERdqhHpl5": { mentalModel: 'Default Privileges 是 PG 的"自动授权"——"以后这个用户/角色创建的所有表/视图/序列，自动给另一个角色授予这些权限"。一次设置，以后自动生效。', sections: [{ title: 'ALTER DEFAULT PRIVILEGES', content: '语法：ALTER DEFAULT PRIVILEGES FOR ROLE creator IN SCHEMA public GRANT SELECT ON TABLES TO readonly; 含义：creator 用户在 public schema 中创建的所有表，自动给 readonly 用户 SELECT 权限。对 SEQUENCES/TYPES/FUNCTIONS 同理。查看当前默认权限：\\ddp。典型场景：应用部署用户（migrator）跑迁移创建的表，自动让应用用户（app）有 CRUD 权限。' }],
    diagnosis: [
      { symptom: 'ALTER DEFAULT PRIVILEGES 后新创建表仍无权限', cause: 'DEFAULT PRIVILEGES 按创建者角色分——对特定创建者生效。用其他角色（如 postgres 或 migrate_user）创建表则不受影响。', fix: '确认创建表角色：SELECT current_user; 确保对应角色 DEFAULT PRIVILEGES 已设。\ddp 检查。为所有相关 creator 设置。' },
      { symptom: 'DEFAULT PRIVILEGES 设错给了所有人 SELECT', cause: 'GRANT ... TO PUBLIC——PUBLIC 是所有角色默认成员，任何人都有该权限。', fix: '撤销：ALTER DEFAULT PRIVILEGES ... REVOKE SELECT ON TABLES FROM PUBLIC; 仅授权特定角色。\ddp 确认。定期审计符合最小权限原则。' },
    ],
  exercises: [{ level: '基础', task: '设置默认权限：migrator 用户创建的表自动给 app 用户授予 SELECT, INSERT, UPDATE, DELETE', hint: 'ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT ... TO app', answer: 'ALTER DEFAULT PRIVILEGES FOR ROLE migrator IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app; ALTER DEFAULT PRIVILEGES FOR ROLE migrator IN SCHEMA public GRANT USAGE ON SEQUENCES TO app; 之后 migrator 跑的 CREATE TABLE 自动授给 app。' }] },
};