import { excalidrawArrow, excalidrawBox, excalidrawScene, excalidrawText } from '../excalidraw-helpers';
import type { TeachingLesson } from '../teaching-types';
import { K8S_TEACHING_4_12 } from './teaching-4-12';

const palette = { blue: '#e7f5ff', yellow: '#fff3bf', green: '#d3f9d8', purple: '#f3d9fa', red: '#ffe3e3', cyan: '#d0ebff' };

const K8S_STAGE_ONE_DIAGRAMS: Record<string, string> = {
  'overview': excalidrawScene([
    excalidrawText('k8s-ov-title', 120, 14, 'Kubernetes 集群鸟瞰：控制面管期望，节点跑容器', 24, 560),
    excalidrawBox('k8s-ov-cluster', 48, 52, 704, 268, '#f8fafc'),
    excalidrawText('k8s-ov-cluster-label', 340, 58, 'Cluster 集群', 18, 120),
    excalidrawBox('k8s-ov-cp', 248, 88, 304, 88, palette.yellow),
    excalidrawText('k8s-ov-cp-t', 278, 108, 'Control Plane 控制面\nAPI / Scheduler / etcd', 16, 244),
    excalidrawBox('k8s-ov-n1', 72, 196, 168, 96, palette.blue),
    excalidrawText('k8s-ov-n1-t', 96, 218, 'Node A\nkubelet\nPod Pod', 15, 120),
    excalidrawBox('k8s-ov-n2', 316, 196, 168, 96, palette.blue),
    excalidrawText('k8s-ov-n2-t', 340, 218, 'Node B\nkubelet\nPod Pod Pod', 15, 120),
    excalidrawBox('k8s-ov-n3', 560, 196, 168, 96, palette.blue),
    excalidrawText('k8s-ov-n3-t', 584, 218, 'Node C\nkubelet\nPod', 15, 120),
    excalidrawArrow('k8s-ov-a1', 400, 176, 0, 16),
    excalidrawArrow('k8s-ov-a2', 320, 176, -80, 16),
    excalidrawArrow('k8s-ov-a3', 480, 176, 80, 16),
    excalidrawText('k8s-ov-note', 120, 338, '你通过 kubectl 对控制面说话，控制面把 Pod 调度到合适节点', 18, 560),
  ]),
  'why-k8s': excalidrawScene([
    excalidrawText('k8s-why-title', 130, 14, '为什么用 K8s：从「人肉运维」到「声明期望状态」', 24, 540),
    excalidrawBox('k8s-why-left', 48, 72, 300, 220, palette.red),
    excalidrawText('k8s-why-left-h', 130, 88, '没有编排时', 20, 136),
    excalidrawText('k8s-why-left-b', 72, 124, 'SSH 每台机器手动启停\n挂了一个要人发现\n扩容要逐台装环境\n配置漂移难追踪', 16, 252),
    excalidrawBox('k8s-why-right', 452, 72, 300, 220, palette.green),
    excalidrawText('k8s-why-right-h', 534, 88, '有 Kubernetes 时', 20, 136),
    excalidrawText('k8s-why-right-b', 476, 124, '写 replicas: 3 即可\nPod 挂了自动重建\nHPA 按负载扩缩\nGitOps 管期望状态', 16, 252),
    excalidrawArrow('k8s-why-arrow', 354, 182, 90, 0, '#0b7285'),
    excalidrawText('k8s-why-bottom', 160, 312, '适合：多服务、多副本、要自愈和弹性；不适合：单脚本硬上集群', 17, 480),
  ]),
  'introduction': excalidrawScene([
    excalidrawText('k8s-intro-title', 150, 14, '入门路径：先懂容器，再懂对象，最后动手部署', 24, 520),
    excalidrawBox('k8s-intro-s1', 78, 108, 140, 72, palette.cyan),
    excalidrawText('k8s-intro-s1-t', 98, 128, '① 容器\n镜像/隔离', 16, 100),
    excalidrawBox('k8s-intro-s2', 268, 148, 140, 72, palette.blue),
    excalidrawText('k8s-intro-s2-t', 288, 168, '② 核心对象\nPod/Node', 16, 100),
    excalidrawBox('k8s-intro-s3', 458, 108, 140, 72, palette.yellow),
    excalidrawText('k8s-intro-s3-t', 478, 128, '③ 工作负载\nDeployment', 16, 100),
    excalidrawBox('k8s-intro-s4', 598, 188, 140, 72, palette.green),
    excalidrawText('k8s-intro-s4-t', 618, 208, '④ 暴露服务\nService', 16, 100),
    excalidrawArrow('k8s-intro-a1', 224, 144, 38, 28),
    excalidrawArrow('k8s-intro-a2', 414, 172, 38, -28),
    excalidrawArrow('k8s-intro-a3', 604, 144, -38, 28),
    excalidrawText('k8s-intro-note', 140, 292, '路线图从左到右是认知顺序；动手时 often 从 Deployment + Service 反推', 17, 520),
  ]),
  'key-concepts': excalidrawScene([
    excalidrawText('k8s-kc-title', 120, 14, '关键术语：从外到内一层包一层', 24, 560),
    excalidrawBox('k8s-kc-outer', 88, 72, 624, 248, '#f8fafc'),
    excalidrawText('k8s-kc-outer-l', 360, 78, 'Cluster', 18, 80),
    excalidrawBox('k8s-kc-ns', 148, 108, 504, 196, palette.purple),
    excalidrawText('k8s-kc-ns-l', 360, 114, 'Namespace', 16, 100),
    excalidrawBox('k8s-kc-node', 208, 144, 384, 132, palette.blue),
    excalidrawText('k8s-kc-node-l', 360, 150, 'Node（物理/虚拟机）', 16, 160),
    excalidrawBox('k8s-kc-pod', 288, 180, 224, 72, palette.yellow),
    excalidrawText('k8s-kc-pod-l', 320, 198, 'Pod（最小调度单元）', 16, 160),
    excalidrawBox('k8s-kc-ctr', 348, 212, 104, 28, palette.green),
    excalidrawText('k8s-kc-ctr-l', 362, 216, 'Container', 14, 76),
    excalidrawText('k8s-kc-note', 120, 338, '先记住 Pod≠Container：Pod 是 K8s 调度的盒子，里面可跑 1+ 容器', 17, 560),
  ]),
  'containers': excalidrawScene([
    excalidrawText('k8s-ctr-title', 130, 14, '容器：镜像是指南，容器是正在跑的实例', 24, 540),
    excalidrawBox('k8s-ctr-image', 88, 88, 180, 100, palette.yellow),
    excalidrawText('k8s-ctr-image-t', 108, 108, 'Image 镜像\n只读模板\nnginx:1.25', 16, 140),
    excalidrawBox('k8s-ctr-host', 48, 220, 704, 88, '#e2e8f0'),
    excalidrawText('k8s-ctr-host-t', 320, 248, 'Host 宿主机 OS + 容器运行时', 16, 200),
    excalidrawBox('k8s-ctr-c1', 88, 196, 120, 72, palette.blue),
    excalidrawText('k8s-ctr-c1-t', 108, 214, '容器 A\n独立进程', 15, 80),
    excalidrawBox('k8s-ctr-c2', 248, 196, 120, 72, palette.blue),
    excalidrawText('k8s-ctr-c2-t', 268, 214, '容器 B\n独立进程', 15, 80),
    excalidrawBox('k8s-ctr-c3', 408, 196, 120, 72, palette.blue),
    excalidrawText('k8s-ctr-c3-t', 428, 214, '容器 C\n独立进程', 15, 80),
    excalidrawArrow('k8s-ctr-a1', 178, 188, 0, 24),
    excalidrawArrow('k8s-ctr-a2', 178, 188, 160, 24),
    excalidrawArrow('k8s-ctr-a3', 178, 188, 320, 24),
    excalidrawText('k8s-ctr-note', 120, 328, 'K8s 不造容器，它编排已打包好的镜像；Docker/containerd 负责真正运行', 17, 520),
  ]),
  'first-deploy': excalidrawScene([
    excalidrawText('k8s-fd-title', 120, 14, '首次部署：一条 YAML 声明期望，集群负责落地', 24, 560),
    excalidrawBox('k8s-fd-you', 300, 56, 200, 56, palette.cyan),
    excalidrawText('k8s-fd-you-t', 340, 72, '你 + kubectl apply', 16, 120),
    excalidrawBox('k8s-fd-yaml', 300, 132, 200, 56, palette.yellow),
    excalidrawText('k8s-fd-yaml-t', 330, 148, 'deployment.yaml\nreplicas: 2', 16, 140),
    excalidrawBox('k8s-fd-api', 300, 208, 200, 56, palette.purple),
    excalidrawText('k8s-fd-api-t', 340, 224, 'API Server 收单', 16, 120),
    excalidrawBox('k8s-fd-dep', 300, 284, 200, 56, palette.blue),
    excalidrawText('k8s-fd-dep-t', 330, 300, 'Deployment 控制器', 16, 140),
    excalidrawBox('k8s-fd-pods', 248, 360, 304, 56, palette.green),
    excalidrawText('k8s-fd-pods-t', 290, 376, '2 个 Pod 在 Node 上 Running', 16, 220),
    excalidrawArrow('k8s-fd-a1', 400, 116, 0, 12),
    excalidrawArrow('k8s-fd-a2', 400, 192, 0, 12),
    excalidrawArrow('k8s-fd-a3', 400, 268, 0, 12),
    excalidrawArrow('k8s-fd-a4', 400, 344, 0, 12),
    excalidrawText('k8s-fd-note', 120, 432, '验证：kubectl get deploy,po — 看 READY 列是否 2/2', 17, 520),
  ]),
};

const K8S_STAGE_TWO_DIAGRAMS: Record<string, string> = {
  'alternatives': excalidrawScene([
    excalidrawText('k8s-alt-title', 100, 14, '编排方案对比：不是只有 K8s 一条路', 24, 560),
    excalidrawBox('k8s-alt-k8s', 48, 72, 200, 120, palette.yellow),
    excalidrawText('k8s-alt-k8s-t', 68, 92, 'Kubernetes\n生态最大\n学习曲线陡', 16, 160),
    excalidrawBox('k8s-alt-nomad', 280, 72, 200, 120, palette.blue),
    excalidrawText('k8s-alt-nomad-t', 300, 92, 'HashiCorp Nomad\n更轻量\n混合负载', 16, 160),
    excalidrawBox('k8s-alt-ecs', 512, 72, 200, 120, palette.green),
    excalidrawText('k8s-alt-ecs-t', 532, 92, 'AWS ECS/Fargate\nAWS 原生\nvendor lock-in', 16, 160),
    excalidrawBox('k8s-alt-swarm', 164, 220, 200, 88, palette.red),
    excalidrawText('k8s-alt-swarm-t', 184, 240, 'Docker Swarm\n简单但边缘化\n适合遗留小集群', 16, 160),
    excalidrawBox('k8s-alt-you', 396, 220, 200, 88, palette.cyan),
    excalidrawText('k8s-alt-you-t', 416, 240, '选型看：团队技能\n云厂商绑定\n社区与招聘', 16, 160),
    excalidrawText('k8s-alt-note', 120, 328, 'K8s 不是唯一答案；路线图学 K8s 是因为它是事实标准和技能通用性最高', 17, 560),
  ]),
  'setting-up': excalidrawScene([
    excalidrawText('k8s-su-title', 130, 14, '搭建 K8s：三条常见路径，目标都是 kubectl 能连上 API', 23, 540),
    excalidrawBox('k8s-su-you', 320, 56, 160, 48, palette.cyan),
    excalidrawText('k8s-su-you-t', 360, 72, '你要一个集群', 16, 80),
    excalidrawBox('k8s-su-managed', 48, 148, 200, 100, palette.green),
    excalidrawText('k8s-su-managed-t', 68, 168, '托管云\nGKE/EKS/AKS\n控制面云厂商管', 16, 160),
    excalidrawBox('k8s-su-local', 280, 148, 200, 100, palette.yellow),
    excalidrawText('k8s-su-local-t', 300, 168, '本地学习\nkind/minikube\n笔记本里跑', 16, 160),
    excalidrawBox('k8s-su-self', 512, 148, 200, 100, palette.purple),
    excalidrawText('k8s-su-self-t', 532, 168, '自建\nkubeadm/k3s\n自己管控制面', 16, 160),
    excalidrawArrow('k8s-su-a1', 360, 108, -120, 36),
    excalidrawArrow('k8s-su-a2', 400, 108, 0, 36),
    excalidrawArrow('k8s-su-a3', 440, 108, 120, 36),
    excalidrawBox('k8s-su-kcfg', 248, 280, 304, 56, palette.blue),
    excalidrawText('k8s-su-kcfg-t', 290, 296, 'kubeconfig → kubectl get nodes 成功', 16, 220),
    excalidrawArrow('k8s-su-a4', 148, 252, 180, 36),
    excalidrawArrow('k8s-su-a5', 380, 252, 0, 24),
    excalidrawArrow('k8s-su-a6', 612, 252, -180, 36),
  ]),
  'managed-provider': excalidrawScene([
    excalidrawText('k8s-mp-title', 90, 14, '选托管 K8s：按「已在哪家云」优先，再比运维与成本', 23, 580),
    excalidrawBox('k8s-mp-gke', 48, 64, 200, 140, palette.blue),
    excalidrawText('k8s-mp-gke-t', 68, 84, 'GKE\nGoogle Cloud\n✓ 与 GCP 服务集成\n✓ Autopilot 省运维', 15, 160),
    excalidrawBox('k8s-mp-eks', 280, 64, 200, 140, palette.yellow),
    excalidrawText('k8s-mp-eks-t', 300, 84, 'EKS\nAWS\n✓ IAM/VPC 原生\n✓ 招聘市场大', 15, 160),
    excalidrawBox('k8s-mp-aks', 512, 64, 200, 140, palette.green),
    excalidrawText('k8s-mp-aks-t', 532, 84, 'AKS\nAzure\n✓ AD/企业集成\n✓ Windows 节点', 15, 160),
    excalidrawBox('k8s-mp-criteria', 120, 228, 520, 88, '#f8fafc'),
    excalidrawText('k8s-mp-criteria-t', 140, 244, '对比维度：区域可用性 · 控制面 SLA · 节点单价 · 团队现有云账号 · 合规要求', 16, 480),
    excalidrawText('k8s-mp-note', 120, 332, '托管 = 控制面由云厂商运维；你只关心 Node 池、网络、RBAC 和应用', 17, 560),
  ]),
  'local-cluster': excalidrawScene([
    excalidrawText('k8s-lc-title', 120, 14, '本地集群：在笔记本里模拟真实 K8s，零云成本练手', 24, 540),
    excalidrawBox('k8s-lc-laptop', 248, 56, 304, 200, '#f1f5f9'),
    excalidrawText('k8s-lc-laptop-l', 360, 64, '你的笔记本电脑', 16, 80),
    excalidrawBox('k8s-lc-kind', 272, 96, 120, 64, palette.yellow),
    excalidrawText('k8s-lc-kind-t', 288, 112, 'kind\nDocker 里\n起 K8s 节点', 14, 88),
    excalidrawBox('k8s-lc-mini', 408, 96, 120, 64, palette.blue),
    excalidrawText('k8s-lc-mini-t', 424, 112, 'minikube\nVM/容器\n单节点', 14, 88),
    excalidrawBox('k8s-lc-cp', 288, 176, 224, 56, palette.purple),
    excalidrawText('k8s-lc-cp-t', 310, 192, '控制面 + Worker（都在本机）', 15, 180),
    excalidrawArrow('k8s-lc-a1', 400, 268, 0, 24),
    excalidrawBox('k8s-lc-kubectl', 300, 296, 200, 48, palette.green),
    excalidrawText('k8s-lc-kubectl-t', 340, 312, 'kubectl apply 练部署', 16, 120),
    excalidrawText('k8s-lc-note', 120, 364, '学习首选 kind 或 minikube；别用 prod kubeconfig 做实验', 17, 520),
  ]),
  'pods': excalidrawScene([
    excalidrawText('k8s-pod-title', 150, 14, 'Pod：K8s 调度的盒子，容器共享网络与存储', 24, 520),
    excalidrawBox('k8s-pod-boundary', 180, 72, 440, 200, palette.yellow),
    excalidrawText('k8s-pod-boundary-l', 340, 78, 'Pod（共享 IP / localhost）', 16, 120),
    excalidrawBox('k8s-pod-app', 208, 112, 160, 80, palette.blue),
    excalidrawText('k8s-pod-app-t', 232, 132, '主容器\nnginx:alpine', 16, 112),
    excalidrawBox('k8s-pod-side', 392, 112, 160, 80, palette.cyan),
    excalidrawText('k8s-pod-side-t', 416, 132, 'Sidecar\n日志采集', 16, 112),
    excalidrawBox('k8s-pod-vol', 280, 208, 240, 48, palette.green),
    excalidrawText('k8s-pod-vol-t', 300, 224, '共享 Volume（可选）', 16, 200),
    excalidrawBox('k8s-pod-node', 48, 296, 704, 48, '#e2e8f0'),
    excalidrawText('k8s-pod-node-t', 300, 312, 'Node 上 kubelet 负责创建/销毁 Pod', 16, 200),
    excalidrawText('k8s-pod-note', 120, 364, 'Pod 是 ephemeral：删了 IP 就变；所以前面要 Service 做稳定入口', 17, 520),
  ]),
  'replicasets': excalidrawScene([
    excalidrawText('k8s-rs-title', 120, 14, 'ReplicaSet：盯住 replicas 数字，少了就补 Pod', 24, 540),
    excalidrawBox('k8s-rs-rs', 280, 56, 240, 72, palette.yellow),
    excalidrawText('k8s-rs-rs-t', 310, 72, 'ReplicaSet\nspec.replicas: 3', 16, 180),
    excalidrawBox('k8s-rs-p1', 88, 168, 120, 72, palette.blue),
    excalidrawText('k8s-rs-p1-t', 112, 188, 'Pod-abc', 16, 72),
    excalidrawBox('k8s-rs-p2', 340, 168, 120, 72, palette.blue),
    excalidrawText('k8s-rs-p2-t', 364, 188, 'Pod-def', 16, 72),
    excalidrawBox('k8s-rs-p3', 592, 168, 120, 72, palette.blue),
    excalidrawText('k8s-rs-p3-t', 616, 188, 'Pod-ghi', 16, 72),
    excalidrawArrow('k8s-rs-a1', 340, 132, -180, 32),
    excalidrawArrow('k8s-rs-a2', 400, 132, 0, 32),
    excalidrawArrow('k8s-rs-a3', 460, 132, 180, 32),
    excalidrawBox('k8s-rs-dead', 340, 280, 120, 56, palette.red),
    excalidrawText('k8s-rs-dead-t', 360, 296, 'Pod 挂了', 16, 80),
    excalidrawArrow('k8s-rs-a4', 400, 336, 0, -96, '#e8590c'),
    excalidrawText('k8s-rs-note', 120, 352, 'Deployment 管 ReplicaSet 管 Pod；日常改 Deployment，很少直接改 RS', 17, 560),
  ]),
};

const K8S_STAGE_THREE_DIAGRAMS: Record<string, string> = {
  'running-apps': excalidrawScene([
    excalidrawText('k8s-ra-title', 120, 14, '运行应用：按「要不要状态/要不要跑完就停」选控制器', 23, 540),
    excalidrawBox('k8s-ra-dep', 48, 80, 160, 100, palette.green),
    excalidrawText('k8s-ra-dep-t', 68, 96, 'Deployment\n无状态 Web\n长期运行', 15, 120),
    excalidrawBox('k8s-ra-sts', 248, 80, 160, 100, palette.purple),
    excalidrawText('k8s-ra-sts-t', 268, 96, 'StatefulSet\nMySQL/Kafka\n稳定身份+盘', 15, 120),
    excalidrawBox('k8s-ra-job', 448, 80, 160, 100, palette.yellow),
    excalidrawText('k8s-ra-job-t', 468, 96, 'Job\n迁移/批处理\n跑完即 Success', 15, 120),
    excalidrawBox('k8s-ra-cron', 648, 80, 160, 100, palette.cyan),
    excalidrawText('k8s-ra-cron-t', 668, 96, 'CronJob\n定时备份\n周期触发 Job', 15, 120),
    excalidrawBox('k8s-ra-q', 120, 220, 520, 72, '#f8fafc'),
    excalidrawText('k8s-ra-q-t', 140, 236, '选型三问：① 副本可互换吗？ ② 需要固定 Pod 名/盘吗？ ③ 任务是长期服务还是跑完就停？', 16, 480),
    excalidrawText('k8s-ra-note', 120, 312, '裸 Pod 只适合调试；生产一律用控制器声明期望状态', 17, 560),
  ]),
  'deployments': excalidrawScene([
    excalidrawText('k8s-dep-title', 110, 14, 'Deployment：滚动升级，一次换一批 Pod', 24, 560),
    excalidrawText('k8s-dep-t0', 48, 56, 't0', 16, 40),
    excalidrawBox('k8s-dep-v1a', 80, 72, 72, 56, palette.blue),
    excalidrawText('k8s-dep-v1a-t', 96, 88, 'v1', 16, 40),
    excalidrawBox('k8s-dep-v1b', 168, 72, 72, 56, palette.blue),
    excalidrawText('k8s-dep-v1b-t', 184, 88, 'v1', 16, 40),
    excalidrawBox('k8s-dep-v1c', 256, 72, 72, 56, palette.blue),
    excalidrawText('k8s-dep-v1c-t', 272, 88, 'v1', 16, 40),
    excalidrawArrow('k8s-dep-a0', 400, 100, 80, 0),
    excalidrawText('k8s-dep-t1', 488, 56, 't1 更新镜像', 16, 100),
    excalidrawBox('k8s-dep-mix1', 520, 72, 72, 56, palette.blue),
    excalidrawText('k8s-dep-mix1-t', 536, 88, 'v1', 16, 40),
    excalidrawBox('k8s-dep-mix2', 600, 72, 72, 56, palette.green),
    excalidrawText('k8s-dep-mix2-t', 616, 88, 'v2', 16, 40),
    excalidrawBox('k8s-dep-mix3', 680, 72, 72, 56, palette.green),
    excalidrawText('k8s-dep-mix3-t', 696, 88, 'v2', 16, 40),
    excalidrawText('k8s-dep-t2', 488, 148, 't2 完成', 16, 80),
    excalidrawBox('k8s-dep-v2a', 520, 164, 72, 56, palette.green),
    excalidrawText('k8s-dep-v2a-t', 536, 180, 'v2', 16, 40),
    excalidrawBox('k8s-dep-v2b', 600, 164, 72, 56, palette.green),
    excalidrawText('k8s-dep-v2b-t', 616, 180, 'v2', 16, 40),
    excalidrawBox('k8s-dep-v2c', 680, 164, 72, 56, palette.green),
    excalidrawText('k8s-dep-v2c-t', 696, 180, 'v2', 16, 40),
    excalidrawBox('k8s-dep-cmd', 248, 248, 304, 48, palette.yellow),
    excalidrawText('k8s-dep-cmd-t', 280, 264, 'kubectl rollout status / undo', 16, 240),
    excalidrawText('k8s-dep-note', 120, 320, 'maxUnavailable / maxSurge 控制换 Pod 节奏；失败可 rollout undo', 17, 560),
  ]),
  'statefulsets': excalidrawScene([
    excalidrawText('k8s-sts-title', 100, 14, 'StatefulSet：有序启动 + 稳定网络身份 + 专属存储', 23, 560),
    excalidrawBox('k8s-sts-0', 72, 88, 140, 120, palette.purple),
    excalidrawText('k8s-sts-0-t', 92, 104, 'web-0\n固定主机名\nPVC-0', 15, 100),
    excalidrawBox('k8s-sts-1', 248, 88, 140, 120, palette.purple),
    excalidrawText('k8s-sts-1-t', 268, 104, 'web-1\n等 0 Ready\nPVC-1', 15, 100),
    excalidrawBox('k8s-sts-2', 424, 88, 140, 120, palette.purple),
    excalidrawText('k8s-sts-2-t', 444, 104, 'web-2\n等 1 Ready\nPVC-2', 15, 100),
    excalidrawArrow('k8s-sts-a1', 216, 148, 24, 0),
    excalidrawArrow('k8s-sts-a2', 392, 148, 24, 0),
    excalidrawBox('k8s-sts-headless', 248, 232, 240, 56, palette.cyan),
    excalidrawText('k8s-sts-headless-t', 268, 248, 'Headless Service\nweb-0.web, web-1.web…', 16, 200),
    excalidrawText('k8s-sts-note', 120, 312, '删 web-1 再建仍叫 web-1、仍挂 PVC-1；适合数据库、ZK、ES', 17, 560),
  ]),
  'configmaps': excalidrawScene([
    excalidrawText('k8s-cm-title', 100, 14, 'ConfigMap 注入：同镜像，不同环境靠配置分叉', 24, 540),
    excalidrawBox('k8s-cm-cm', 80, 88, 200, 120, palette.yellow),
    excalidrawText('k8s-cm-cm-t', 100, 104, 'ConfigMap\nLOG_LEVEL=debug\napp.properties', 15, 160),
    excalidrawBox('k8s-cm-pod', 480, 88, 240, 120, palette.blue),
    excalidrawText('k8s-cm-pod-t', 500, 104, 'Pod 容器\n读配置运行', 16, 200),
    excalidrawArrow('k8s-cm-a1', 284, 128, 60, -20),
    excalidrawText('k8s-cm-env', 300, 96, 'envFrom', 14, 60),
    excalidrawArrow('k8s-cm-a2', 284, 168, 60, 20),
    excalidrawText('k8s-cm-vol', 300, 176, 'volumeMount', 14, 90),
    excalidrawBox('k8s-cm-dev', 48, 248, 200, 56, palette.green),
    excalidrawText('k8s-cm-dev-t', 68, 264, 'dev ConfigMap', 16, 160),
    excalidrawBox('k8s-cm-prod', 280, 248, 200, 56, palette.red),
    excalidrawText('k8s-cm-prod-t', 300, 264, 'prod ConfigMap', 16, 160),
    excalidrawText('k8s-cm-note', 120, 328, '非敏感配置放 ConfigMap；密码/token 用 Secret，别混放', 17, 560),
  ]),
  'jobs': excalidrawScene([
    excalidrawText('k8s-job-title', 130, 14, 'Job：跑完就停，成功次数达标即完成', 24, 520),
    excalidrawBox('k8s-job-job', 300, 56, 200, 64, palette.yellow),
    excalidrawText('k8s-job-job-t', 330, 72, 'Job\ncompletions: 1', 16, 140),
    excalidrawArrow('k8s-job-a1', 400, 124, 0, 24),
    excalidrawBox('k8s-job-pod', 300, 152, 200, 72, palette.blue),
    excalidrawText('k8s-job-pod-t', 330, 168, 'Pod 执行脚本\n迁移/导出/计算', 16, 140),
    excalidrawArrow('k8s-job-a2', 400, 228, 0, 24),
    excalidrawBox('k8s-job-ok', 300, 256, 200, 64, palette.green),
    excalidrawText('k8s-job-ok-t', 330, 272, 'Succeeded ✓\nJob 不再重启', 16, 140),
    excalidrawBox('k8s-job-fail', 560, 152, 160, 72, palette.red),
    excalidrawText('k8s-job-fail-t', 580, 168, 'Failed\n按 backoff\n重试', 15, 120),
    excalidrawText('k8s-job-note', 120, 344, '与 Deployment 不同：Job Pod 结束后不「维持 N 个副本」', 17, 520),
  ]),
  'secrets': excalidrawScene([
    excalidrawText('k8s-sec-title', 110, 14, 'Secret：敏感数据单独存，注入时仍要防泄露', 24, 540),
    excalidrawBox('k8s-sec-vault', 72, 80, 200, 128, palette.red),
    excalidrawText('k8s-sec-vault-t', 92, 96, 'Secret\nDB_PASSWORD\nAPI_TOKEN\n(base64 非加密!)', 15, 160),
    excalidrawBox('k8s-sec-pod', 480, 80, 240, 128, palette.blue),
    excalidrawText('k8s-sec-pod-t', 500, 96, 'Pod\nenv: 从 Secret 引用\nvolume: 挂载文件', 15, 200),
    excalidrawArrow('k8s-sec-a1', 276, 144, 196, 0),
    excalidrawBox('k8s-sec-no', 120, 248, 280, 64, palette.yellow),
    excalidrawText('k8s-sec-no-t', 140, 264, '✗ 写进镜像  ✗ 明文 commit Git', 16, 240),
    excalidrawBox('k8s-sec-yes', 440, 248, 280, 64, palette.green),
    excalidrawText('k8s-sec-yes-t', 460, 264, '✓ External Secrets  ✓ 轮换+滚动重启', 16, 240),
    excalidrawText('k8s-sec-note', 120, 332, 'RBAC 限制谁 get secret；生产考虑 Sealed Secrets / 云 KMS', 17, 560),
  ]),
};


export const KUBERNETES_TEACHING_LESSONS: Record<string, TeachingLesson> = {
  qLeEEwBvlGt1fP5Qcreah: {
    heading: 'Kubernetes 概览：一个会自愈的容器舰队',
    subheading: '先建立「集群 = 控制面 + 多节点 + 很多 Pod」这张地图，再记名词。',
    scene: '你刚接触云原生，听说 K8s 能管几百个微服务。打开文档满屏 Pod、Node、Deployment——需要先有一张鸟瞰图，才知道这些词各在哪一层。',
    core: 'Kubernetes = 用声明式 API 管理容器化应用；控制面维护期望状态，节点上的 kubelet 把 Pod 跑起来。',
    metaphor: '像港口调度中心：塔台（控制面）看全局，泊位（节点）停船（Pod），不用你逐条船手动指挥。',
    mistake: '不要把 K8s 当成「安装 Docker 的另一种方式」。它管的是跨机器的调度、副本和自愈，不是单机打包。',
    confusion: 'K8s 与 Docker 的关系：Docker/containerd 负责跑容器；K8s 负责决定「跑几个、跑在哪、挂了怎么办」。',
    experiment: '有测试集群时执行 `kubectl get nodes` 和 `kubectl get pods -A`，对照图里控制面与节点的关系。',
    route: [
      { label: '看全局', title: 'Cluster 是最外层', text: '一个集群有多台 Node，上面跑很多 Pod；控制面不跑你的业务容器，只管调度。' },
      { label: '认控制面', title: 'API Server 是入口', text: 'kubectl、CI、控制器都通过 API 提交「期望状态」，etcd 存这份期望。' },
      { label: '认节点', title: 'Node 是真正干活的机器', text: '每台 Node 上有 kubelet，负责把 Pod 拉起来、汇报健康。' },
      { label: '连起来', title: 'Pod 是最小调度单元', text: '你很少直接管 Pod，而是通过 Deployment 等控制器声明「要几个副本」。' },
    ],
    rawDiagram: K8S_STAGE_ONE_DIAGRAMS.overview,
  },
  'q-Ky0ietZGpyUcBQfh-BJ': {
    heading: '为什么用 Kubernetes：什么时候值得上集群',
    subheading: '不是为了追热门，而是当你的痛点是「多副本、自愈、弹性」时，人肉运维会崩。',
    scene: '团队从 1 台服务器扩到 10 台，半夜服务挂了靠人醒来看日志；发版要 SSH 逐台重启。你开始想：有没有办法写「我要 3 个副本」，剩下的交给系统？',
    core: '上 K8s 的价值 = 声明期望状态 + 控制器持续对齐 + 节点级故障时自动迁移/重建。',
    metaphor: '像从「每个房间手动开关灯」升级到「设定亮度 80%，传感器自动补光」——你管目标，系统管执行。',
    mistake: '不要给单文件脚本、单节点 demo 硬上 K8s。集群本身有学习成本和运维成本，小项目用 Docker Compose 往往更合适。',
    confusion: 'K8s 不能替代良好的应用设计。无状态、健康检查、配置外置，这些做好了 K8s 才发挥价值。',
    experiment: '列出你当前项目的 3 个痛点（扩容/回滚/故障恢复），逐条对照 K8s 能否解决；不能解决的别强行迁移。',
    route: [
      { label: '痛点对照', title: '多副本与滚动发布', text: 'Deployment 可以零停机换版本；手工 SSH 很难保证顺序和安全。' },
      { label: '自愈', title: '进程挂了自动重建', text: '控制器发现 Pod 不在 Running，会在别的 Node 再起一个。' },
      { label: '弹性', title: 'HPA/VPA 按负载扩缩', text: '流量高峰自动加 Pod，低谷缩回去，省机器也省人工盯盘。' },
      { label: '何时不上', title: '简单场景别过度', text: '单机、无高可用需求、团队没人会运维集群时，先别上。' },
    ],
    rawDiagram: K8S_STAGE_ONE_DIAGRAMS['why-k8s'],
  },
  y7KjVfSI6CAduyHd4mBFT: {
    heading: '入门介绍：这门课怎么学 Kubernetes',
    subheading: '按「容器 → 对象 → 工作负载 → 网络」走，比一上来背 100 个 CRD 更稳。',
    scene: '路线图把 Introduction 放在最前，不是让你一次学完，而是告诉你：后面每一章都在这张学习路径的某一站。',
    core: '学习顺序 = 理解容器隔离 → 认识 Pod/Node → 用 Deployment 跑应用 → 用 Service 暴露访问。',
    metaphor: '像学开车：先认方向盘（容器），再认档位和仪表（K8s 对象），最后上路练习（kubectl apply）。',
    mistake: '不要跳过容器基础直接啃 YAML。不懂镜像和进程隔离，Pod 的边界会一直模糊。',
    confusion: 'Introduction 是 meta 节点（怎么学），不是某个 K8s API 对象；别去 kubectl get introduction。',
    experiment: '在路线图里标出你已学过的 Docker/容器章节；缺的先补 Docker 路线再回来。',
    route: [
      { label: '第一站', title: '容器与镜像', text: '明白「镜像只读、容器运行、宿主机共享内核」。' },
      { label: '第二站', title: 'Pod 与 Node', text: 'Pod 是调度单位；Node 是跑 Pod 的机器。' },
      { label: '第三站', title: 'Deployment', text: '声明 replicas，让控制器维持副本数。' },
      { label: '第四站', title: 'Service / Ingress', text: '稳定访问入口，Pod IP 会变，Service 不会。' },
    ],
    rawDiagram: K8S_STAGE_ONE_DIAGRAMS.introduction,
  },
  '9oo2fxTM2_p0VYPBroqxa': {
    heading: '关键概念与术语：Cluster 套 Namespace 套 Node 套 Pod',
    subheading: '术语多是因为层次多；用「从外到内」记，比按字母背效率高十倍。',
    scene: '读官方文档遇到 Cluster、Namespace、Pod、ReplicaSet、Service——它们不是平级名词，而是嵌套关系。',
    core: '记忆锚点：Cluster > Namespace > Node > Pod > Container；控制器（Deployment 等）是「管家」，不是物理层。',
    metaphor: '像俄罗斯套娃：最外是园区（Cluster），楼里分楼层（Namespace），每层有工位（Node），工位上放项目箱（Pod），箱里是工具（Container）。',
    mistake: '不要把 Pod 和 Container 画等号。一个 Pod 里可以跑 sidecar（如日志采集），它们共享网络 namespace。',
    confusion: 'ReplicaSet 常被 Deployment 包住，日常 kubectl 很少直接操作 RS；知道它是「维持 Pod 副本数的底层」即可。',
    experiment: '执行 `kubectl get ns,node,pod -A`（有集群时），把输出每一列对应到套娃图的某一层。',
    route: [
      { label: 'Cluster', title: '整个 K8s 集群', text: '包含所有控制面组件和 Worker Node。' },
      { label: 'Namespace', title: '逻辑隔离', text: 'dev/staging/prod 或团队划分；不是物理机隔离。' },
      { label: 'Node', title: 'Worker 机器', text: '可以是云 VM、物理机；上面跑 kubelet。' },
      { label: 'Pod / Container', title: '最小调度 vs 实际进程', text: 'K8s 调度 Pod；容器运行时启动 Container。' },
    ],
    rawDiagram: K8S_STAGE_ONE_DIAGRAMS['key-concepts'],
  },
  HGmeYvRf7_XusZl_K4x9k: {
    heading: '容器：Kubernetes 编排的基本单位',
    subheading: 'K8s 管的是「已经容器化的应用」；先搞清镜像与实例，再谈 Pod。',
    scene: '你要把 Java 服务上 K8s，CI 已经打出 `myapp:1.2.0` 镜像。集群不会编译代码，只会拉镜像、起容器、监控健康。',
    core: 'Container = 镜像的运行实例；Image = 只读分层文件系统 + 启动命令；同一镜像可起多个隔离容器。',
    metaphor: '镜像像蛋糕模具和配方，容器是每次烤出来的蛋糕——配方不变，可以烤很多个，互不影响。',
    mistake: '不要在容器里写死 IP 或本地路径当持久存储。容器随时可能被删重建，数据要走 Volume。',
    confusion: 'Docker 是常用构建/运行工具，K8s 集群里常用 containerd/CRI-O 跑容器；概念一样，实现可不同。',
    experiment: '本地 `docker run -d nginx:alpine` 后 `docker ps`，再 `docker stop`；体会「实例可销毁、镜像还在」。',
    route: [
      { label: '镜像', title: '只读模板', text: 'tag 标识版本；集群通过 imagePullPolicy 决定何时拉取。' },
      { label: '容器', title: '运行中的进程', text: '有独立 PID 空间；默认与宿主机隔离网络/文件系统（可配置）。' },
      { label: '宿主机', title: 'Node 上的运行时', text: 'kubelet 告诉运行时「起这个镜像」；不是 K8s 自己起进程。' },
      { label: '进 K8s', title: 'Pod 包一个或多个容器', text: 'Sidecar 模式：主应用 + 日志/代理容器同 Pod 共享 localhost。' },
    ],
    rawDiagram: K8S_STAGE_ONE_DIAGRAMS.containers,
  },
  zrbSJa3k7a3TE0aYbWi9c: {
    heading: '部署第一个应用：kubectl apply 一条 YAML',
    subheading: '第一次部署的目标不是搞懂全部字段，而是跑通「声明 → 控制器 → Pod Running」。',
    scene: '本地 kind/minikube 或云厂商托管集群已就绪。你写一份 Deployment，replicas: 2，想看到两个 Pod 变绿。',
    core: '首次部署链路 = YAML 描述期望 → kubectl apply → API 入库 → Deployment 控制器创建 Pod → kubelet 拉镜像启动。',
    metaphor: '像餐厅点单：你写菜单（YAML），前台（API）接单，厨房长（Deployment）分单，厨师（kubelet）做菜。',
    mistake: '不要 kubectl run 裸 Pod 就以为部署完成。没有控制器，Pod 删了不会回来，也不方便滚动升级。',
    confusion: 'apply 是声明式（保留字段合并），create 是一次性；日常推荐 apply + Git 管理 YAML。',
    experiment: '最小 Deployment + `kubectl apply -f deploy.yaml`，然后 `kubectl get deploy,pod -w` 观察 Pod 从 Pending 到 Running。',
    route: [
      { label: '写 YAML', title: 'apiVersion/kind/metadata/spec', text: '最少：Deployment + 容器 image + replicas。' },
      { label: 'apply', title: '提交期望状态', text: 'kubectl 把对象发给 API Server；etcd 持久化。' },
      { label: '控制器', title: 'Deployment 管 ReplicaSet 管 Pod', text: '实际创建 Pod 的是 ReplicaSet；Deployment 管版本。' },
      { label: '验证', title: 'get / describe / logs', text: 'READY 2/2、Events 无 ImagePullBackOff 即成功第一步。' },
    ],
    rawDiagram: K8S_STAGE_ONE_DIAGRAMS['first-deploy'],
  },
  '3fzuXKH7az_LVnmnoXB1p': {
    heading: 'Kubernetes 替代方案：什么时候不必上 K8s',
    subheading: 'Nomad、ECS、Swarm 各有定位；了解替代方案才能确认 K8s 是否真适合你的场景。',
    scene: '老板问「一定要用 Kubernetes 吗？」——你需要能说出：团队规模、云绑定、运维能力不同，答案可以不同。',
    core: 'K8s 胜在生态与通用技能；替代方案往往在「更轻」或「与某云深度绑定」上更省事。',
    metaphor: '像选交通工具：K8s 是高铁枢纽（换乘多、通达全国）；ECS 像市内地铁（AWS 里很顺）；Nomad 像城际巴士（轻量跨数据中心）。',
    mistake: '不要无脑「K8s 万能」。小团队、单服务、无弹性需求时，Serverless 或 Compose 可能更省。',
    confusion: 'OpenShift、Rancher 是 K8s 发行版/管理平台，不是 K8s 的替代品，而是 K8s 之上的产品。',
    experiment: '列你项目 3 条需求（多副本/多云/Job 调度），查 Nomad 与 ECS 文档各 10 分钟，写一句「选 K8s 的理由」。',
    route: [
      { label: 'K8s', title: '事实标准', text: 'CNCF 生态、Helm、Operator、招聘市场——学路线图的主因。' },
      { label: 'Nomad', title: '轻量调度', text: '可调度容器+二进制+Java；HashiCorp 栈整合好。' },
      { label: 'ECS/Fargate', title: 'AWS 原生', text: '已在 AWS 且不想养控制面时很香。' },
      { label: 'Swarm', title: '遗留/simple', text: 'Docker 内置编排，新项目一般不再选。' },
    ],
    rawDiagram: K8S_STAGE_TWO_DIAGRAMS.alternatives,
  },
  '3OpGaQhyNtk1n1MLp-tlb': {
    heading: '搭建 Kubernetes：先选路径，再拿 kubeconfig',
    subheading: '搭建不是装一个软件，而是让 kubectl 能稳定访问一个 API Server。',
    scene: '你要开始动手了：公司用 AWS，家里笔记本想练——两条路都要会，但别混 kubeconfig。',
    core: '搭建集群 = 控制面可用 + Worker 就绪 + 本机 kubectl context 指向正确集群。',
    metaphor: '像开通银行账户：可以选国有大行（托管）、社区银行（自建）、沙箱账户（本地 kind）——关键是卡（kubeconfig）别刷错店。',
    mistake: '不要把 prod 和 dev 的 kubeconfig 放同一 default context；误操作 delete 代价巨大。',
    confusion: '「安装 K8s」在托管场景里你装的是 CLI 和权限，不是 etcd 和 API Server 本身。',
    experiment: '本地 `kind create cluster` 或 `minikube start`，然后 `kubectl config get-contexts` 看 context 名称。',
    route: [
      { label: '托管', title: '云控制台点几下', text: 'GKE/EKS/AKS 创建集群，下载 kubeconfig 或 aws az gcloud 登录。' },
      { label: '本地', title: 'kind / minikube', text: '学习、CI 集成测试首选；删集群也只是一条 delete 命令。' },
      { label: '自建', title: 'kubeadm / k3s', text: '裸机或 VM 自己管控制面；运维成本高。' },
      { label: '验证', title: 'get nodes', text: '节点 Ready、系统 Pod Running 再部署业务。' },
    ],
    rawDiagram: K8S_STAGE_TWO_DIAGRAMS['setting-up'],
  },
  'qSatCdBTDXPu-IFWzUI99': {
    heading: '选托管 K8s：GKE、EKS、AKS 怎么选',
    subheading: '不是比谁的 API Server 更强——控制面都是云厂商运维，比的是你的云栈与团队。',
    scene: '公司主账号在 AWS，却有人提议 GKE「性能更好」——选型应先看 IAM、VPC、账单、合规，而不是 kubectl 命令差异。',
    core: '托管 K8s 选型 = 已有云厂商优先 + 区域与 SLA + 节点定价 + 团队熟悉度。',
    metaphor: '像选手机运营商：套餐（节点价）、覆盖（区域）、和现有号码（IAM/AD）能否一键登录，比手机壳颜色重要。',
    mistake: '不要为「学 K8s」在 prod 开三家云各一套集群；学习用本地 kind，prod 跟主云走。',
    confusion: 'Managed K8s 仍要你自己管：Node 池大小、网络策略、RBAC、Ingress、应用 YAML——不是「全托管到不用管」。',
    experiment: '打开三家文档的 Pricing 页，对比同规格 3 节点月费；再查你公司现有云账号是哪家。',
    route: [
      { label: 'GKE', title: 'GCP 用户首选', text: 'Autopilot 省节点运维；与 Cloud SQL、Pub/Sub 集成顺。' },
      { label: 'EKS', title: 'AWS 用户首选', text: 'IAM Role for SA、VPC CNI、Fargate 可选。' },
      { label: 'AKS', title: 'Azure / 企业 AD', text: '与 AAD、Azure DevOps 整合；混合云场景常见。' },
      { label: '决策', title: '对齐现有云', text: '跨云 K8s 可以，但网络和身份成本会翻倍。' },
    ],
    rawDiagram: K8S_STAGE_TWO_DIAGRAMS['managed-provider'],
  },
  YaIs8lquWIe1D7RCUBZmC: {
    heading: '安装本地集群：kind 与 minikube 练手',
    subheading: '在笔记本里跑完整 K8s 控制面，不花云钱，随便 destroy 重建。',
    scene: '晚上想学 kubectl apply，但公司 prod 不能碰——本地 kind 集群 2 分钟建好，错了就 `kind delete cluster`。',
    core: '本地集群 = Docker/VM 里跑 K8s 组件 + kubeconfig 自动写入 ~/.kube/config。',
    metaphor: '像驾驶模拟器：路况（Pod 调度）是真的，撞车（删 namespace）不扣驾照分。',
    mistake: '不要本地集群默认装 metrics/logging 全家桶占满内存；先最小集群，需要再加 addon。',
    confusion: 'kind 的「节点」是 Docker 容器；minikube 可以是 docker/driver 或 vm driver——对 kubectl 来说都像真集群。',
    experiment: '`kind create cluster --name learn` → `kubectl cluster-info` → 部署 nginx Deployment 验证。',
    route: [
      { label: 'kind', title: '多节点模拟', text: '适合 CI；一个命令起 control-plane + worker 容器。' },
      { label: 'minikube', title: '单节点入门', text: 'dashboard addon 友好；教程多。' },
      { label: '资源', title: 'CPU/RAM 预留', text: '至少 4GB 可用内存，否则系统 Pod Pending。' },
      { label: '隔离', title: '独立 context', text: 'context 命名含 learn/dev，避免切错 prod。' },
    ],
    rawDiagram: K8S_STAGE_TWO_DIAGRAMS['local-cluster'],
  },
  '-d2PIXm0V_Iehe8cws8zK': {
    heading: 'Pod：最小调度单元，不是最小容器',
    subheading: 'K8s 调度的对象是 Pod；一个 Pod 里可以跑多个协作容器。',
    scene: '你写了一个 pod.yaml 里两个 container：app + log-shipper。它们共享 Pod IP，localhost 能互访——这是 Pod 存在的理由之一。',
    core: 'Pod = 一组共享网络/存储命名空间的容器；调度、IP、生命周期以 Pod 为单位。',
    metaphor: '像合租公寓的一个房间：室友（容器）共用门牌号（Pod IP）和客厅（Volume），各睡各床（独立进程）。',
    mistake: '不要生产环境长期跑裸 Pod（无控制器）。Pod 被删不会自动回来，Deployment 才会维持副本。',
    confusion: 'Pod vs Container：Docker run 起的是容器；K8s 包一层 Pod 才能调度、挂 Service、做探针。',
    experiment: '`kubectl run tmp --image=nginx --restart=Never` → `kubectl get pod -o wide` 看 IP；delete 后再 get 确认消失。',
    route: [
      { label: '边界', title: 'Pod 是调度单位', text: 'Scheduler 选 Node 放 Pod，不是放单个 container。' },
      { label: '多容器', title: 'Sidecar 模式', text: '主应用 + 代理/日志/ mesh 同 Pod 共享 localhost。' },
      { label: '生命周期', title: 'Pending→Running→Succeeded/Failed', text: 'Failed 看 Events 和 logs。' },
      { label: '下一步', title: '用 Deployment 管 Pod', text: '直接写 Pod YAML 只适合调试。' },
    ],
    rawDiagram: K8S_STAGE_TWO_DIAGRAMS.pods,
  },
  'IF09l0-pryGpMbDt__ocr': {
    heading: 'ReplicaSet：维持「要几个 Pod」的守门员',
    subheading: '它盯着 label selector 匹配的 Pod 数量，少了就创建，多了就删。',
    scene: 'Deployment 把 replicas 改成 5，背后 ReplicaSet 发现只有 3 个 Pod 带正确 label——立刻再建 2 个。',
    core: 'ReplicaSet = selector + replicas 数字 + Pod template；控制循环让实际副本数逼近期望。',
    metaphor: '像停车场管理员：车位牌写「要有 3 辆车」（replicas），少一辆就引导新车进场，多一辆就清走。',
    mistake: '不要手动 kubectl create rs 又同时用 Deployment 管同一套 label——会打架。日常只操作 Deployment。',
    confusion: 'ReplicaSet 取代旧 ReplicationController；API 版本 apps/v1，字段类似但 RS 支持更丰富的 selector。',
    experiment: 'Deployment replicas:2 → scale to 4 → `kubectl get rs,pod` 看 RS 名下 Pod 数量变化。',
    route: [
      { label: 'selector', title: '按 label 认亲', text: 'app=myweb 的 Pod 才算数。' },
      { label: 'replicas', title: '期望数字', text: 'spec.replicas 是目标，status 是当前。' },
      { label: 'template', title: '新 Pod 长什么样', text: '缺 Pod 时按 template 创建。' },
      { label: 'Deployment', title: '你通常不直接改 RS', text: 'Deployment 滚动升级会换 RS，保留历史便于回滚。' },
    ],
    rawDiagram: K8S_STAGE_TWO_DIAGRAMS.replicasets,
  },
  '1MdrzhktCWjpmxiYYBdz7': {
    heading: '运行应用：选对 Workload 控制器',
    subheading: 'K8s 跑应用不是 kubectl run 就完事——Deployment、StatefulSet、Job 各管一类场景。',
    scene: '你要上集群：API 服务要 3 副本滚动发版，MySQL 要有稳定盘， nightly 还要跑报表 Job——三种需求，三种控制器。',
    core: '运行应用 = 用合适的控制器声明 Pod 模板 + 副本/完成策略 + 更新策略，让控制循环维持期望状态。',
    metaphor: '像餐厅分工：Deployment 是回转寿司（盘子可互换）；StatefulSet 是包厢订位（座位号固定）；Job 是一次性外送（送完收工）。',
    mistake: '不要所有服务都 Deployment。有状态、要固定网络标识或顺序启动的，StatefulSet 或 Operator 更合适。',
    confusion: 'DaemonSet 也算运行应用（每节点一个 Pod），本 stage 先掌握 Deployment/StatefulSet/Job 三角。',
    experiment: '同一 nginx 镜像分别用 Deployment 和 Job 各 apply 一次，对比 `kubectl get deploy,job,pod` 生命周期差异。',
    route: [
      { label: 'Deployment', title: '无状态长期服务', text: 'Web/API，Pod 可随意替换，滚动升级。' },
      { label: 'StatefulSet', title: '有状态有序', text: '数据库、消息队列，Pod 名与 PVC 绑定。' },
      { label: 'Job', title: '跑完即停', text: '批处理、迁移，Succeeded 即结束。' },
      { label: 'CronJob', title: '定时 Job', text: '备份、清理，按 cron 表达式触发。' },
    ],
    rawDiagram: K8S_STAGE_THREE_DIAGRAMS['running-apps'],
  },
  'TUGQX7y1gs-aKPge2F1NU': {
    heading: 'Deployment：无状态应用的标准跑法',
    subheading: '声明 replicas 和镜像版本，升级时逐步替换 Pod，而不是一次全杀。',
    scene: '发版 v2：你希望 traffic 始终有 Pod 扛着，旧 Pod 一批批下线、新 Pod 一批批上线——Deployment 的 RollingUpdate 干的就是这个。',
    core: 'Deployment → ReplicaSet → Pod；改 spec.template 触发 rollout，Kubernetes 按 maxSurge/maxUnavailable 换 Pod。',
    metaphor: '像换班：夜班不能全走才叫白班，每次只换一部分人，服务不断档。',
    mistake: '不要不设 readinessProbe 就加大流量。新 Pod 还没 Ready 就被 Service 转发，会 502。',
    confusion: 'Deployment 管版本；底层 ReplicaSet 名字带 hash，每次 template 变会新建 RS，旧的留作回滚历史。',
    experiment: '`kubectl set image deploy/demo app=demo:v2` → `kubectl rollout status` → 故意失败再 `rollout undo`。',
    route: [
      { label: '声明', title: 'replicas + template', text: '镜像、资源、探针都在 template 里。' },
      { label: '升级', title: 'RollingUpdate', text: '默认 strategy，可改 surge/unavailable。' },
      { label: '观察', title: 'rollout status/history', text: '看 ReplicaSet 代数与 Pod 代数。' },
      { label: '回滚', title: 'rollout undo', text: '回到上一版 template。' },
    ],
    rawDiagram: K8S_STAGE_THREE_DIAGRAMS.deployments,
  },
  AJiRBEaKU8qYEm0fqN389: {
    heading: 'StatefulSet：Pod 有名字、有顺序、有专属盘',
    subheading: '当 Pod 不能随意互换——数据库主从、Kafka broker——用 StatefulSet。',
    scene: 'MySQL 集群：mysql-0 必须先于 mysql-1 Ready；删了 mysql-1 重建仍叫 mysql-1，数据还在 PVC-1 上。',
    core: 'StatefulSet = 有序部署/缩容 + 稳定 network ID（pod-name.service）+ volumeClaimTemplates 每 Pod 一块盘。',
    metaphor: '像酒店长包房：201、202 房间号固定，不能今天 201 住张三明天换李四还叫 201 但行李换人了——StatefulSet 保证「房号与行李（PVC）」对应。',
    mistake: '不要用 Deployment 跑需要稳定存储的单实例数据库；Pod 重建后挂错盘或名乱掉很难排查。',
    confusion: 'StatefulSet 的 Service 通常要 headless（clusterIP: None），这样 DNS 才能解析到每个 Pod A 记录。',
    experiment: '部署一个简单的 StatefulSet（如 nginx + volumeClaimTemplates），删中间 Pod 看名字与 PVC 是否复用。',
    route: [
      { label: '身份', title: 'pod-name-ordinal', text: 'web-0、web-1 固定，不是随机 hash。' },
      { label: '顺序', title: '0→1→2 启动', text: '缩容也逆序，避免有状态逻辑乱套。' },
      { label: '存储', title: 'volumeClaimTemplates', text: '每个 ordinal 自动创建 PVC。' },
      { label: '网络', title: 'Headless Service', text: 'peer 发现、主从选举常用。' },
    ],
    rawDiagram: K8S_STAGE_THREE_DIAGRAMS.statefulsets,
  },
  u24UlZKI86vaguj_VpMv1: {
    heading: 'ConfigMap 注入：配置与镜像分离',
    subheading: '同一份镜像跑 dev/staging/prod，差在 ConfigMap 里的键值或文件。',
    scene: 'Spring 的 application.properties、Nginx 的 nginx.conf——不想打进镜像，改一行配置就要 rebuild；用 ConfigMap 挂进去或 env 注入。',
    core: 'ConfigMap 存非敏感配置 → Pod 通过 env / envFrom / volumeMount 读取 → 改 ConfigMap 后需滚动 Pod 才生效（除非用 reloader）。',
    metaphor: '像给同一款手机换 SIM 卡：手机（镜像）不变，号卡（ConfigMap）决定连哪个网。',
    mistake: '不要把密码放 ConfigMap；etcd 里仍是明文，RBAC 漏了就能被 get。',
    confusion: 'ConfigMap 更新不会自动热加载进已运行容器；volume 挂载有延迟，env 注入要重建 Pod。',
    experiment: '创建 ConfigMap + Deployment envFrom；改 ConfigMap 后 rollout restart，看容器内 env 变化。',
    route: [
      { label: '创建', title: 'kubectl create cm', text: 'key-value 或整文件 content。' },
      { label: 'env', title: '单个或 envFrom', text: '适合简单键值。' },
      { label: 'volume', title: '挂载成文件', text: '适合 nginx.conf、yaml 配置。' },
      { label: '分环境', title: 'dev/prod 不同 CM', text: '同 Deployment，换 CM 引用即可。' },
    ],
    rawDiagram: K8S_STAGE_THREE_DIAGRAMS.configmaps,
  },
  r3fzAN5DzratAKnnT8hzb: {
    heading: 'Job：一次性任务，成功算完',
    subheading: '不是 7×24 挂着，而是跑脚本到 exit 0，Job 标记 Completed。',
    scene: '凌晨跑数据迁移、导出报表、跑 ML 训练一次——跑完容器退出，不需要 Deployment 那种「永远维持 3 副本」。',
    core: 'Job = 创建 Pod 执行 → 成功次数达到 completions → Job Complete；失败按 backoffLimit 重试。',
    metaphor: '像外卖一单：骑手送到（Succeeded）这单就结，不会像门店一样 24 小时营业。',
    mistake: '不要用 Deployment replicas:1 代替 Job——容器 exit 后 Deployment 会再起，Job 则应在成功后停止。',
    confusion: 'CronJob 是 Job 的定时器；parallelism/completions 控制并行份数和总成功次数。',
    experiment: '`kubectl create job demo --image=busybox -- echo done` → 看 Pod Succeeded → Job COMPLETIONS 1/1。',
    route: [
      { label: '适用', title: '批处理/迁移', text: '有明确结束点的工作。' },
      { label: '字段', title: 'completions / parallelism', text: '跑几份、几份并行。' },
      { label: '重试', title: 'backoffLimit', text: '失败 Pod 重试上限。' },
      { label: '清理', title: 'ttlSecondsAfterFinished', text: '完成后自动删 Job/Pod。' },
    ],
    rawDiagram: K8S_STAGE_THREE_DIAGRAMS.jobs,
  },
  'S0CwGC2gMG-SqnLNldqBD': {
    heading: 'Secret：敏感配置要单独管',
    subheading: 'API Key、数据库密码、TLS 证书——用 Secret，并假设 etcd 内仍是需 RBAC 保护的数据。',
    scene: '把 DB 密码写进 Deployment YAML 明文 commit 到 Git——任何人 clone 就能连库；应 Secret + 限制 RBAC + 不进 Git。',
    core: 'Secret 与 ConfigMap 用法类似（env/volume），但类型为 Opaque/tls/dockerconfigjson；默认仅 base64 编码，不是加密。',
    metaphor: '像保险柜放钥匙：比贴墙上（镜像/env 明文）好，但保险柜本身要上锁（RBAC、加密 at rest）。',
    mistake: '不要以为 base64 等于加密；`kubectl get secret -o yaml` 一眼能解。生产用 KMS、Sealed Secrets、External Secrets。',
    confusion: 'Secret vs ConfigMap：敏感 vs 非敏感；用法相同，审计与权限应更严。',
    experiment: '创建 Secret，`kubectl create secret generic db --from-literal=pass=xxx`，Deployment 用 valueFrom.secretKeyRef 引用。',
    route: [
      { label: '创建', title: 'generic / tls / docker', text: '按类型选；别 commit 明文。' },
      { label: '注入', title: 'env 或 volume', text: '与 ConfigMap 语法类似。' },
      { label: '权限', title: 'RBAC 最小化', text: '谁能 get/list secret。' },
      { label: '生产', title: '加密与轮换', text: '启用 encryption at rest；换 Secret 后滚动 Pod。' },
    ],
    rawDiagram: K8S_STAGE_THREE_DIAGRAMS.secrets,
  },
  ...K8S_TEACHING_4_12,
};

export function hasKubernetesTeachingLesson(id: string): boolean {
  return id in KUBERNETES_TEACHING_LESSONS;
}

export function getKubernetesTeachingLesson(id: string): TeachingLesson | undefined {
  return KUBERNETES_TEACHING_LESSONS[id];
}
